name: Generate ASCII Art

on: push

jobs: 
    first_job:
            runs-on: ubuntu-latest
            steps:
            
            - name: Checkout Repo
              uses: actions/checkout@v5

            - name: List Repo files
              run: ls -lrta
            
            - name: Executing shell script
              run: ./ascii-script.sh 

            #- name: List files
            #  run: ls 
            
            #- name: Read file
            #  run: cat README.md